name: Backup SQLite and Logs

on:
  schedule:
    - cron: '0 */6 * * *'  # Cada 6 horas
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Download DB and Logs from Render
      env:
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        # Instalar CLI de Render (opcional)
        # curl -fsSL https://cli.render.com/install.sh | bash
        
        # Crear directorio para backups
        mkdir -p backups
        
        # 1. Descargar base de datos (simulación - en Render free no hay persistencia)
        # Esto es un placeholder - necesitarías una solución real para obtener los archivos
        echo "Backup simulado - implementa tu método para obtener los archivos"
        
        # 2. Comprimir lo que tengamos
        tar -czvf backups/backup-$(date +%Y%m%d-%H%M).tar.gz persistent_data/
        
        # 3. Subir a GitHub
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add backups/
        git commit -m "Backup automático $(date +%Y%m%d-%H%M)"
        git push
